version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 18
  pre_build:
    commands:
      - cd astro
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_DEFAULT_REGION=ap-northeast-1
      - env
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm sst deploy --stage dev
